function DMCtoRGB = importfile(filename, dataLines)
    %IMPORTFILE Import data from a text file
    %  DMCTORGB = IMPORTFILE(FILENAME) reads data from text file FILENAME
    %  for the default selection.  Returns the data as a table.
    %  
    %  DMCTORGB = IMPORTFILE(FILE, DATALINES) reads data for the specified
    %  row interval(s) of text file FILENAME. Specify DATALINES as a
    %  positive scalar integer or a N-by-2 array of positive scalar integers
    %  for dis-contiguous row intervals.
    %  
    %  Example:
    %  DMCtoRGB = importfile("C:\Users\josef\Documents\Bildreproduktion\Cross-Stitch\Resources\DMCtoRGB.csv", [431, 431]);
    %  
    %  See also READTABLE.
    %  
% Auto-generated by MATLAB on 12-Feb-2020 22:45:51

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
dataLines = [431, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 7);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Var1", "Description", "Var3", "Var4", "Var5", "Var6", "Var7"];
opts.SelectedVariableNames = "Description";
opts.VariableTypes = ["string", "string", "string", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Description", "Var3", "Var4", "Var5", "Var6", "Var7"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Description", "Var3", "Var4", "Var5", "Var6", "Var7"], "EmptyFieldRule", "auto");

% Import the data
DMCtoRGB = readtable(filename, opts);

end